extend type Query {
  searchDocument(searchSet: InputSearch!, page: Int!): TupleSearchResult
}

input InputSearch {
  search: [String]!,
  contributor: [String]!,
  contributorRole: [String]!,
  creator: [String]!,
  creatorOrganizationName: [String]!,
  publisher: [String]!,
  year: [String]!
}

type TupleSearchResult {
  foundDocument: Int,
  totalPage: Int,
  currPage: Int,
  documentRelevance: [DocumentRelevance],
  efficiencyInputSearch: EfficiencyInputSearch,
  errorMessage: String,
}

type DocumentRelevance {
  documentId: Int,
  relevanceScore: Float
}

type EfficiencyInputSearch {
  fulltext: String,
  keywordDeepcut: [KeywordDeepcut]
}

type KeywordDeepcut {
  keyword: String,
  used: Boolean
}
