extend type Query {
  documentStatusMultiple: [DocumentStatus]
  documentStatus(documentId: Int!): DocumentStatus
  pageInDocument(documentId: Int!): [Page]
  keywordInPage(pageId: Int!, documentId: Int!): PageDetail
}

extend type Mutation {
  insertPreterm(newPreterm: String!, pageId: Int!): PreTerm,
  editPreterm(newPreterm: String!, preTermId: Int!): PreTerm,
  deletePreterm(preTermId: Int!): Boolean,
  changeStatusPage(pageId: Int!, status: Int!): Boolean,
  startTfDjango(documentId: Int!): ResultStartTF
}

type ResultStartTF {
  status: Boolean,
  message: String,
}

type DocumentStatus {
  documentId: Int,
  name: String,
  version: Int,
  status: Int,
  pages: [Page]
}

type Page {
  pageId: Int,
  index: Int,
  name: String,
  status: Int
}

type PageDetail {
  PreTerms: [PreTerm],
  maxPage: Int,
  image: String
}

type PreTerm {
  preTermId: Int,
  preTerm: String,
}

type Image {
  image: String
}
