extend type Query {
  documentStatusMultiple: [DocumentStatus]
  documentStatus(documentId: Int!): DocumentStatus
  pageInDocument(documentId: Int!): [Page]
  keywordInPage(pageId: Int!, documentId: Int!): PageDetail
  amountPage(documentId: Int!): ResultAmountPage
}

extend type Mutation {
  insertPreterm(newPreterm: String!, pageId: Int!): PreTerm,
  editPreterm(newPreterm: String!, preTermId: Int!): PreTerm,
  deletePreterm(preTermId: Int!): Boolean,
  overridePerterm(newInformation: InputSeleceOverridePerterm!, documentId: Int!): ResultOverridePerterm,
  changeStatusPage(pageId: Int!, status: Int!): Boolean,
  startTfDjango(documentId: Int!): ResultStartTF
}

input InputSeleceOverridePerterm {
  overide: [InputOverridePerterm],
  newPage: [InputNewPagePerTerm]
}

input InputOverridePerterm {
  pageId: Int!,
  token: [String]
}

input InputNewPagePerTerm {
  pageIndex: Int!,
  name: String,
  token: [String]
}

type ResultOverridePerterm {
  overidestatus: Boolean,
  addNewStatus: [ResultAddNewStatus]
}

type ResultAmountPage{
  firstPage: Int,
  lastPage: Int,
  status: Int
}

type ResultAddNewStatus {
  pageIndex: Int,
  documentId: Int,
  status: Boolean
}

type ResultStartTF {
  status: Boolean,
  message: String,
}

type DocumentStatus {
  documentId: Int,
  name: String,
  version: Int,
  status: Int,
  pages: [Page],
  title: String,
  publish:String,
}

type Page {
  pageId: Int,
  index: Int,
  name: String,
  status: Int
}

type PageDetail {
  PreTerms: [PreTerm],
  amountPage: Int,
  pageId: Int,
  image: String
}

type PreTerm {
  preTermId: Int,
  preTerm: String,
}

type Image {
  image: String
}
