env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
  "no-console": "off",
  semi: ["error", "never"],
  "import/no-named-as-default": 0,
  "import/no-named-as-default-member": 0,
  max-len: ["error", { "code": 150 }]
}
