extend type Query {
  document(pk: Int!): TupleResultDocument
  documents: TupleResultDocuments
}

type TupleResultDocuments {
  statusQuery: Boolean
  documents: [ResultDocument]
}

type TupleResultDocument{
  statusQuery: Boolean
  document: ResultDocument
}

type ResultDocument {
  statusQuery: Boolean,
  id: Int,
  name: String,
  version: Int,
  pageStart: Int,
  amountPage: Int,
  path: String,
  pathImage: String,
  title: String,
  titleAlternative: String,
  tableOfContents: String,
  abstract: String,
  note: String,
  format: String,
  formatExtent: String,
  identifierURL: String,
  identifierISBN: String,
  source: String,
  language: String,
  coverageSpatial: String,
  coverageTemporal: String,
  coverageTemporalYear: String,
  rights: String,
  rightsAccess: String,
  thesisDegreeName: String,
  thesisDegreeLevel: String,
  thesisDegreeDiscipline: String,
  thesisDegreeGrantor: String,
  recCreateAt: String,
  recCreateBy:  Int,
  recModifiedAt: String,
  recModifiedBy: Int,
  keyword: [String],
  relation: [String],
  type: [String],
  creator: String,
  creatorOrgName: String,
  publisher: String,
  publisherEmail: String,
  contributor: String,
  contributorEmail: String,
  issuedDate: String,
  tag: [Tag],
  image: String,
  status: Int,
}

type Tag {
  tag: String!,
  scoreId: Int
}

type File {
  filename: String!
  mimetype: String!
  encoding: String!
  pathFile: String!
}

extend type Mutation {
  addDocument(body: AddDocumentInput!): ResultAddDocument
  uploadDocument(file: Upload!): File!
}

input AddDocumentInput {
  addVersion: Boolean
  startPage: Int!
  name: String!
  path: String!
  DC_relation: [String]
  DC_type: [String]
  DC_title: String!
  DC_title_alternative: String
  DC_description_table_of_contents: String
  DC_description_summary_or_abstract: String
  DC_description_note: String
  DC_format: String
  DC_format_extent: String
  DC_identifier_URL: String
  DC_identifier_ISBN: String
  DC_source: String
  DC_language: String
  DC_coverage_spatial: String
  DC_coverage_temporal: String
  DC_coverage_temporal_year: String
  DC_rights: String
  DC_rights_access: String
  thesis_degree_name: String
  thesis_degree_level: String
  thesis_degree_discipline: String
  thesis_degree_grantor: String
  DC_creator: String
  DC_creator_orgname: String
  DC_publisher: String
  DC_publisher_email: String
  DC_contributor: String
  DC_contributor_role: String
  DC_issued_date: String
}

type ResultAddDocument {
  status: Boolean,
  message: String,
  documentId: Int,
  prevBody: DocumentPrevBody
}

type DocumentPrevBody {
  addVersion: Boolean
  name: String
  path: String
  DC_relation: [String]
  DC_type: [String]
  DC_title: String
  DC_title_alternative: String
  DC_description_table_of_contents: String
  DC_description_summary_or_abstract: String
  DC_description_note: String
  DC_format: String
  DC_format_extent: String
  DC_identifier_URL: String
  DC_identifier_ISBN: String
  DC_source: String
  DC_language: String
  DC_coverage_spatial: String
  DC_coverage_temporal: String
  DC_rights: String
  DC_rights_access: String
  thesis_degree_name: String
  thesis_degree_level: String
  thesis_degree_discipline: String
  thesis_degree_grantor: String
  DC_creator: String
  DC_creator_orgname: String
  DC_publisher: String
  DC_publisher_email: String
  DC_contributor: String
  DC_contributor_role: String
  DC_issued_date: String
  rec_create_by: String
}

