extend type Query {
  tagInDocument(documentId: Int!): [String],
  generateTagForAdd(documentId: Int!, limit: Int): [String]
}

extend type Mutation {
  putDocumentDone(documentID: Int!): Boolean,
  overrideUserKeyword(keywords: [String]!, documentId: Int!): [ResultOverrideUserKeyword]
}

type ResultOverrideUserKeyword {
  keyword: String
  status: Boolean,
  message: String
}
